apiVersion: v1
kind: ConfigMap
metadata:
  name: paygate-config
  namespace: paygate
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_HTTP_PORTS: "8080"
  JWT_ISSUER: "PaymentGateway"
  JWT_AUDIENCE: "PaymentGateway"
  AUTHORIZE_NET_IS_SANDBOX: "true"
