apiVersion: v1
kind: Secret
metadata:
  name: paygate-secrets
  namespace: paygate
type: Opaque
stringData:
  SA_PASSWORD: "PayGate@K8s2024!"
  JWT_KEY: "PaymentGatewayDefaultSecretKey_ChangeInProduction!2024"
  AUTHORIZE_NET_LOGIN_ID: "YOUR_SANDBOX_LOGIN_ID"
  AUTHORIZE_NET_TRANSACTION_KEY: "YOUR_SANDBOX_TRANSACTION_KEY"
