apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-data
  namespace: paygate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentdb
  namespace: paygate
  labels:
    app: paymentdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentdb
  template:
    metadata:
      labels:
        app: paymentdb
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paygate-secrets
                  key: SA_PASSWORD
            - name: MSSQL_PID
              value: "Developer"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: sqlserver-data
              mountPath: /var/opt/mssql
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -C -Q "SELECT 1" -b
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -C -Q "SELECT 1" -b
            initialDelaySeconds: 45
            periodSeconds: 30
            timeoutSeconds: 5
      volumes:
        - name: sqlserver-data
          persistentVolumeClaim:
            claimName: sqlserver-data
---
apiVersion: v1
kind: Service
metadata:
  name: paymentdb
  namespace: paygate
  labels:
    app: paymentdb
spec:
  type: NodePort
  selector:
    app: paymentdb
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 30204
      name: sql
